from app.risk.risk_config import RISK_SCORES


class RiskEngine:
    """
    Calculates an overall risk score and level
    from the alerts generated by the Correlation Engine.
    """

    def __init__(self):

        self.risk_scores = RISK_SCORES

    def calculate_risk(self, alerts):

        score = 0

        for alert in alerts:

            alert_type = alert.get("alert_type")

            score += self.risk_scores.get(alert_type, 0)

        level = self.get_risk_level(score)

        return {

            "score": score,

            "level": level,

            "alert_count": len(alerts),

            "alerts": alerts

        }

    @staticmethod
    def get_risk_level(score):

        if score >= 100:
            return "CRITICAL"

        if score >= 50:
            return "HIGH"

        if score >= 25:
            return "MEDIUM"

        return "LOW"


risk_engine = RiskEngine()