RISK_SCORES = {

    # Authentication
    "MULTIPLE_FAILED_LOGINS": 15,
    "BRUTE_FORCE": 30,
    "MULTIPLE_IP_LOGIN": 20,
    "BUSINESS_HOURS_LOGIN": 10,
    "CONCURRENT_LOGIN": 20,
    "DISABLED_USER_LOGIN": 35,
    "SERVICE_ACCOUNT_LOGIN": 25,
    "MULTIPLE_PROVIDER_LOGIN": 20,

    # IAM
    "IAM_PRIVILEGE_ESCALATION": 50,
    "NEW_ADMIN_USER": 40,
    "ROOT_ACCOUNT_USAGE": 45,
    "MFA_DISABLED": 35,
    "IAM_POLICY_CHANGED": 30,
    "ACCESS_KEY_CREATED": 20,
    "ACCESS_KEY_REACTIVATED": 35,
    "MULTIPLE_IAM_CHANGES": 50,

    # Resource
    "PUBLIC_BUCKET": 35,
    "SECURITY_GROUP_OPEN": 30,
    "INSTANCE_CREATED": 10,
    "INSTANCE_TERMINATED": 10,
    "UNUSUAL_REGION_RESOURCE": 20,
    "LOAD_BALANCER_DELETED": 25,
    "PUBLIC_SNAPSHOT": 30,
    "MULTIPLE_RESOURCE_DELETIONS": 40,

    # Data
    "LARGE_DATA_DOWNLOAD": 25,
    "SENSITIVE_FILE_ACCESS": 30,
    "MULTIPLE_STORAGE_READS": 20,
    "DATA_EXFILTRATION": 60,
    "PUBLIC_DATABASE_SNAPSHOT": 50,
    "MASS_OBJECT_DELETION": 40,
    "CROSS_REGION_COPY": 30,
    "MULTIPLE_DATA_EVENTS": 60,

    # Configuration
    "AUDIT_LOGGING_DISABLED": 50,
    "ENCRYPTION_DISABLED": 50,
    "MFA_ENFORCEMENT_DISABLED": 35,
    "WEAK_PASSWORD_POLICY": 20,
    "SECURITY_SERVICE_DISABLED": 35,
    "BACKUP_DISABLED": 30,
    "RETENTION_POLICY_CHANGED": 20,
    "MULTIPLE_CONFIGURATION_CHANGES": 60,
}